services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      JWT_SECRET: your_super_secret_jwt_key_here
      PORT: 5001
      FRONTEND_URL: http://localhost:3000
      DB_DIALECT: sqlite
      DB_NAME: database.sqlite
    volumes:
      - ./backend/db:/app/db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    depends_on:
      backend:
        condition: service_healthy
